<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Venture;
use App\Models\LandingPage;
use App\Models\SiteMenu;

class MasterVentureAndLandingPagesSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Seed 4 Core Ventures
        $ventures = [
            [
                'name' => 'Digital Terai',
                'slug' => 'digital-terai',
                'tagline' => 'Search Growth & Performance Marketing Agency in Nepal',
                'category' => 'digital_growth',
                'status' => 'published',
                'published' => true,
                'logo' => '/assets/images/companies/digital-terai-logo.svg',
                'cover_image' => '/assets/images/blogs/digital-marketing-roi-analytics.jpg',
                'website_url' => 'https://digitalterai.com',
                'my_role' => 'Founder & Managing Director',
                'founder' => 'Peshal Bhattarai',
                'founded_date' => '2019-01-15',
                'description' => 'A premier digital marketing and search-growth agency based in Kathmandu, Nepal. Focused on organic SEO, performance funnels, technical content, and digital transformation.',
                'content' => "## About Digital Terai\n\nDigital Terai is a specialized performance marketing and SEO agency founded by Peshal Bhattarai. We help startups, SMEs, and international brands dominate organic search and scale customer acquisition funnels.\n\n### Core Capabilities\n- Technical SEO & Site Audits\n- Local & International SEO Architecture\n- Performance Marketing & Paid Funnels\n- Content Strategy & E-E-A-T Optimization\n- Answer Engine Optimization (AEO & GEO)",
                'services' => ['SEO', 'Technical SEO', 'Local SEO', 'Performance Marketing', 'Content Marketing', 'AEO', 'GEO', 'AI Search Optimization'],
                'locations' => ['Kathmandu, Nepal', 'Dubai, UAE'],
                'industries' => ['B2B SaaS', 'E-commerce', 'Healthcare', 'Real Estate', 'Hospitality'],
                'technologies' => ['Google Analytics 4', 'Search Console', 'Ahrefs', 'Semrush', 'Screaming Frog', 'Next.js SEO'],
                'primary_keyword' => 'digital marketing Nepal',
                'secondary_keywords' => ['Digital Terai', 'SEO Nepal', 'SEO agency Nepal', 'growth marketing Nepal'],
                'seo_title' => 'Digital Terai | Growth Digital Marketing & SEO Agency Nepal',
                'meta_description' => 'Digital Terai is a premier search marketing and performance agency in Nepal founded by Peshal Bhattarai.',
                'canonical_url' => 'https://www.peshalb.com.np/ventures/digital-terai',
            ],
            [
                'name' => 'IntechNexus',
                'slug' => 'intechnexus',
                'tagline' => 'Remote Engineering Teams & Enterprise Software Partner',
                'category' => 'technology',
                'status' => 'published',
                'published' => true,
                'logo' => '/assets/images/companies/intechnexus-logo.svg',
                'cover_image' => '/assets/images/blogs/offshore-development-squads.jpg',
                'website_url' => 'https://intechnexus.com',
                'my_role' => 'Founder & Chief Technology Officer',
                'founder' => 'Peshal Bhattarai',
                'founded_date' => '2020-03-01',
                'description' => 'A technology consulting firm offering Remote Engineering Teams as a Service, enterprise SaaS development, AI integration, and digital transformation squads from Kathmandu.',
                'content' => "## About IntechNexus\n\nIntechNexus bridges global tech enterprises with high-caliber software engineering talent in Nepal. Led by Peshal Bhattarai, IntechNexus delivers dedicated agile squads for SaaS product development and legacy code modernization.\n\n### Core Engineering Services\n- Remote Engineering Team as a Service\n- Full-Stack SaaS Product Development\n- AI & LLM Model Integration\n- Legacy Monolith Migration (Laravel & React)\n- Agile Coaching & Delivery Management",
                'services' => ['Remote Team as a Service', 'SaaS Product Development', 'AI Integration', 'Agile Coaching', 'Software Engineering', 'Digital Transformation'],
                'locations' => ['Kathmandu, Nepal', 'Global Remote'],
                'industries' => ['Software & SaaS', 'Fintech', 'AgriTech', 'Healthcare IT'],
                'technologies' => ['Laravel 12', 'Next.js 15', 'TypeScript', 'Node.js', 'Python', 'AWS', 'Docker', 'Kubernetes'],
                'primary_keyword' => 'software development Nepal',
                'secondary_keywords' => ['IntechNexus', 'remote development team Nepal', 'dedicated software developers Nepal', 'remote team as a service'],
                'seo_title' => 'IntechNexus | Remote Engineering Squads & Software Development Nepal',
                'meta_description' => 'IntechNexus provides dedicated remote engineering teams, SaaS development, and AI integration squads from Nepal.',
                'canonical_url' => 'https://www.peshalb.com.np/ventures/intechnexus',
            ],
            [
                'name' => 'BeinSEO Dubai',
                'slug' => 'beinseo-dubai',
                'tagline' => 'International SEO, AEO & Generative Engine Optimization Dubai',
                'category' => 'seo',
                'status' => 'published',
                'published' => true,
                'logo' => '/assets/images/companies/beinseo-logo.svg',
                'cover_image' => '/assets/images/blogs/aeo-geo-search-optimization.jpg',
                'website_url' => 'https://beinseo.ae',
                'my_role' => 'Founder & Principal Consultant',
                'founder' => 'Peshal Bhattarai',
                'founded_date' => '2022-06-10',
                'description' => 'An international SEO and AEO consultancy based in Dubai helping luxury brands, real estate firms, and B2B enterprises rank across Google, ChatGPT, Perplexity, and AI Search.',
                'content' => "## About BeinSEO Dubai\n\nBeinSEO Dubai represents the cutting-edge of Generative Engine Optimization (GEO) and AI Answer Engine Search. Operating in the UAE, BeinSEO empowers enterprises to dominate AI search surfaces.\n\n### Strategic Pillars\n- International & Regional SEO Dubai\n- Answer Engine Optimization (AEO)\n- Generative Engine Optimization (GEO)\n- AI Overview Citation Placement\n- Enterprise Entity & Schema Graphing",
                'services' => ['SEO Consultancy', 'AEO Dubai', 'AI SEO Dubai', 'Generative Engine Optimization', 'International SEO', 'Entity Schema Graphing'],
                'locations' => ['Dubai, UAE', 'Kathmandu, Nepal'],
                'industries' => ['Luxury Real Estate', 'Finance', 'B2B Services', 'Hospitality', 'Off-Plan Properties'],
                'technologies' => ['Schema.org Microdata', 'Perplexity API', 'ChatGPT Optimization', 'Google Search Console'],
                'primary_keyword' => 'SEO consultant Dubai',
                'secondary_keywords' => ['BeinSEO Dubai', 'SEO Dubai', 'AEO Dubai', 'AI SEO Dubai', 'Generative Engine Optimization Dubai'],
                'seo_title' => 'BeinSEO Dubai | International SEO, AEO & AI Search Agency Dubai',
                'meta_description' => 'BeinSEO Dubai specializes in AI Search Optimization, Answer Engine Optimization (AEO), and Enterprise SEO in Dubai.',
                'canonical_url' => 'https://www.peshalb.com.np/ventures/beinseo-dubai',
            ],
            [
                'name' => 'Thoplo Machine',
                'slug' => 'thoplo-machine',
                'tagline' => 'IoT Agritech & Smart Drip Irrigation Automation Venture',
                'category' => 'agritech',
                'status' => 'published',
                'published' => true,
                'logo' => '/assets/images/companies/thoplo-machine-logo.svg',
                'cover_image' => '/assets/images/blogs/smart-agritech-iot-farm.jpg',
                'website_url' => 'https://thoplomachine.com',
                'my_role' => 'Co-Founder & Product Architect',
                'founder' => 'Peshal Bhattarai',
                'founded_date' => '2021-08-20',
                'description' => 'An innovative IoT and agritech hardware/software venture providing automated precision drip irrigation, remote telemetry sensors, and smart agriculture systems in Nepal.',
                'content' => "## About Thoplo Machine\n\nThoplo Machine automates agricultural irrigation across remote commercial farming projects in Nepal. Integrating hardware microcontrollers, telemetry sensors, and cloud dashboards, Thoplo Machine saves up to 60% water while maximizing crop yields.\n\n### Innovation Specs\n- Automated Drip Irrigation Controllers\n- LoRaWAN & Cellular Telemetry Sensors\n- Cloud Farm Analytics Dashboard\n- Solar Powered Micro-Grid Sensors\n- Precision Fertigation Control",
                'services' => ['IoT Sensors', 'Remote Irrigation Automation', 'Telemetry Systems', 'Smart Agritech', 'Cloud Agriculture Dashboards'],
                'locations' => ['Kathmandu, Nepal', 'Pokhara, Nepal'],
                'industries' => ['Commercial Agriculture', 'Horticulture', 'Greenhouses', 'Smart Farms'],
                'technologies' => ['ESP32', 'LoRaWAN', 'MQTT', 'Laravel Cloud API', 'Flutter Mobile App'],
                'primary_keyword' => 'IoT agritech Nepal',
                'secondary_keywords' => ['Thoplo Machine', 'IoT company Nepal', 'smart agriculture Nepal', 'agricultural IoT'],
                'seo_title' => 'Thoplo Machine | Smart Agritech & IoT Farm Automation Nepal',
                'meta_description' => 'Thoplo Machine provides automated drip irrigation controllers and IoT telemetry for smart farming in Nepal.',
                'canonical_url' => 'https://www.peshalb.com.np/ventures/thoplo-machine',
            ],
        ];

        foreach ($ventures as $v) {
            Venture::updateOrCreate(['slug' => $v['slug']], $v);
        }

        // 2. Seed 17 Initial Draft Landing Pages (DRAFT Status per Section 33)
        $landingPages = [
            // Business Consulting
            [
                'title' => 'Business Consulting Services in Nepal',
                'slug' => 'business-consulting-nepal',
                'path' => '/business-consulting/nepal/',
                'category' => 'business',
                'status' => 'draft',
                'published' => false,
                'heading' => 'Strategic Business & Corporate Advisory in Nepal',
                'subheading' => 'Guiding international startups and regional enterprises through setup, compliance, and operational scale.',
                'summary' => 'Comprehensive business advisory for launching and scaling tech companies and commercial operations in Kathmandu, Nepal.',
                'primary_keyword' => 'Business consultant Nepal',
                'seo_title' => 'Business Consultant Nepal | Corporate Advisory & Market Entry',
                'meta_description' => 'Executive business consulting services in Nepal by Peshal Bhattarai.',
            ],
            [
                'title' => 'Company & Business Registration in Nepal',
                'slug' => 'business-registration-nepal',
                'path' => '/business-consulting/nepal/business-registration/',
                'category' => 'business',
                'status' => 'draft',
                'published' => false,
                'heading' => 'IT Company & Business Registration Guide Nepal',
                'subheading' => 'Navigating OCR, Inland Revenue Department (IRD), and FITTA foreign direct investment approvals.',
                'summary' => 'Complete legal guide and consulting framework for registering private limited IT subsidiaries and companies in Nepal.',
                'primary_keyword' => 'Company registration in Nepal',
                'seo_title' => 'Company Registration in Nepal | IT Business Setup Guide',
                'meta_description' => 'Step-by-step business registration and IT company setup guide in Nepal.',
            ],
            // Dubai Business
            [
                'title' => 'Dubai Business Setup & Corporate Formation',
                'slug' => 'dubai-business-setup',
                'path' => '/dubai/business-setup/',
                'category' => 'dubai',
                'status' => 'draft',
                'published' => false,
                'heading' => 'Executive Dubai Freezone & Mainland Business Setup',
                'subheading' => 'Establish 100% foreign-owned UAE entities with 0% corporate tax concessions and Golden Visas.',
                'summary' => 'Strategic corporate formation and company setup advisory for tech founders in Dubai, UAE.',
                'primary_keyword' => 'Business setup in Dubai',
                'seo_title' => 'Business Setup in Dubai | Freezone & Corporate Formation Guide',
                'meta_description' => 'Dubai business setup and corporate advisory by Peshal Bhattarai.',
            ],
            [
                'title' => 'Company Formation in Dubai UAE',
                'slug' => 'dubai-company-formation',
                'path' => '/dubai/company-formation/',
                'category' => 'dubai',
                'status' => 'draft',
                'published' => false,
                'heading' => 'Company Formation & Trade License Advisory Dubai',
                'subheading' => 'IFZA, DMCC, Meydan, and DED mainland corporate licensing.',
                'summary' => 'Expert guidance on selecting freezone jurisdictions and forming trade entities in Dubai.',
                'primary_keyword' => 'Company registration in Dubai',
                'seo_title' => 'Company Registration in Dubai | IFZA & DMCC Freezone Formation',
                'meta_description' => 'Company formation and licensing in Dubai for global tech founders.',
            ],
            [
                'title' => 'Dubai Real Estate Investment for Founders',
                'slug' => 'dubai-real-estate-investment',
                'path' => '/dubai/real-estate-investment/',
                'category' => 'dubai',
                'status' => 'draft',
                'published' => false,
                'heading' => 'Dubai Off-Plan & Luxury Real Estate Investment Strategy',
                'subheading' => 'High-yield ROI models, Golden Visa qualification, and cross-border tech wealth diversification.',
                'summary' => 'Financial modeling and property acquisition advisory in Dubai for international founders.',
                'primary_keyword' => 'Dubai real estate investment',
                'seo_title' => 'Dubai Real Estate Investment Guide | Off-Plan & Luxury Villa ROI',
                'meta_description' => 'Cross-border real estate investment analysis and Dubai off-plan property guide.',
            ],
            // Technology
            [
                'title' => 'Technology Leadership & Engineering Advisory',
                'slug' => 'technology-hub',
                'path' => '/technology/',
                'category' => 'technology',
                'status' => 'draft',
                'published' => false,
                'heading' => 'Enterprise Technology & SaaS Architecture Partner',
                'subheading' => 'Architecting cloud microservices, scaling remote squads, and refactoring legacy monoliths.',
                'summary' => 'Central technology hub detailing fractional CTO leadership and software engineering capabilities.',
                'primary_keyword' => 'Technology consultant Nepal',
                'seo_title' => 'Technology Leadership & Software Engineering Partner',
                'meta_description' => 'Enterprise software architecture and technology consulting by Peshal Bhattarai.',
            ],
            [
                'title' => 'AI Development & Integration Services in Nepal',
                'slug' => 'ai-development-nepal',
                'path' => '/technology/ai-development-nepal/',
                'category' => 'technology',
                'status' => 'draft',
                'published' => false,
                'heading' => 'AI & LLM Model Integration Engineering Nepal',
                'subheading' => 'Deploying custom OpenAI, Claude, and local LLM agents into enterprise software.',
                'summary' => 'Custom AI development and machine learning integration services from Kathmandu.',
                'primary_keyword' => 'AI development Nepal',
                'seo_title' => 'AI Development Nepal | Enterprise LLM & Machine Learning Integration',
                'meta_description' => 'AI model integration and intelligent software development in Nepal.',
            ],
            [
                'title' => 'Software Development Services in Nepal',
                'slug' => 'software-development-nepal',
                'path' => '/technology/software-development-nepal/',
                'category' => 'technology',
                'status' => 'draft',
                'published' => false,
                'heading' => 'Full-Stack Software Development & Cloud Engineering',
                'subheading' => 'Building scalable web applications with Next.js 15, Laravel 12, Node.js, and AWS.',
                'summary' => 'End-to-end software development services from high-velocity engineering squads in Nepal.',
                'primary_keyword' => 'Software development Nepal',
                'seo_title' => 'Software Development Nepal | Full-Stack Web & Cloud Engineering',
                'meta_description' => 'Custom software development services and cloud architecture in Nepal.',
            ],
            [
                'title' => 'SaaS Product Development & Microservices Architecture',
                'slug' => 'saas-development',
                'path' => '/technology/saas-development/',
                'category' => 'technology',
                'status' => 'draft',
                'published' => false,
                'heading' => 'B2B SaaS Product Development & Cloud Engineering',
                'subheading' => 'Multi-tenant architecture, automated subscription billing, and zero-downtime scaling.',
                'summary' => 'End-to-end SaaS product engineering from initial MVP to multi-million user cloud scale.',
                'primary_keyword' => 'SaaS development',
                'seo_title' => 'SaaS Development Services | Scalable B2B Cloud Architecture',
                'meta_description' => 'Custom SaaS product development and cloud multi-tenant engineering.',
            ],
            [
                'title' => 'AI Consultant & Strategy Advisory in Nepal',
                'slug' => 'ai-consultant-nepal',
                'path' => '/technology/ai-consultant-nepal/',
                'category' => 'technology',
                'status' => 'draft',
                'published' => false,
                'heading' => 'Enterprise AI Strategy & LLM Adoption Consulting',
                'subheading' => 'Auditing data pipelines, identifying AI high-ROI use cases, and training engineering teams.',
                'summary' => 'Strategic AI consulting for enterprise leaders evaluating artificial intelligence implementation.',
                'primary_keyword' => 'AI consultant Nepal',
                'seo_title' => 'AI Consultant Nepal | Executive Artificial Intelligence Strategy',
                'meta_description' => 'AI strategy and enterprise machine learning adoption consulting in Nepal.',
            ],
            // Remote / Product
            [
                'title' => 'Remote Development Team as a Service in Nepal',
                'slug' => 'remote-development-team-nepal',
                'path' => '/technology/remote-development-team-nepal/',
                'category' => 'technology',
                'status' => 'draft',
                'published' => false,
                'heading' => 'Dedicated Remote Engineering Squads from Nepal',
                'subheading' => 'Save 55-65% compared to US/UK hiring while managing senior Agile developers.',
                'summary' => 'Hire dedicated full-stack software development squads in Kathmandu.',
                'primary_keyword' => 'remote team as a service',
                'seo_title' => 'Remote Development Team Nepal | Hire Dedicated Software Developers',
                'meta_description' => 'Hire dedicated offshore software development squads in Nepal.',
            ],
            [
                'title' => 'Hire Senior Agile Project Manager in Nepal',
                'slug' => 'project-manager-nepal',
                'path' => '/technology/project-manager-nepal/',
                'category' => 'technology',
                'status' => 'draft',
                'published' => false,
                'heading' => 'Agile Delivery Management & Project Leadership',
                'subheading' => 'Certified Scrum Masters and Technical Product Managers driving sprint velocities.',
                'summary' => 'Hire experienced Agile project managers and Scrum leaders in Kathmandu.',
                'primary_keyword' => 'hire project manager in Nepal',
                'seo_title' => 'Hire Project Manager in Nepal | Agile Scrum & Technical Product Leaders',
                'meta_description' => 'Technical project management and Agile delivery leadership from Nepal.',
            ],
            [
                'title' => 'MVP Development Services for Startups in Nepal',
                'slug' => 'mvp-development-nepal',
                'path' => '/technology/mvp-development-nepal/',
                'category' => 'technology',
                'status' => 'draft',
                'published' => false,
                'heading' => 'Rapid 90-Day MVP Development & Prototype Engineering',
                'subheading' => 'Transforming startup concepts into investor-ready functional SaaS products.',
                'summary' => 'Fast-track MVP product development services for global tech founders.',
                'primary_keyword' => 'MVP development team in Nepal',
                'seo_title' => 'MVP Development Team Nepal | 90-Day Rapid Startup Prototyping',
                'meta_description' => 'Rapid MVP development services and startup prototyping in Nepal.',
            ],
            // Digital Growth
            [
                'title' => 'Digital Growth & Search Marketing Hub',
                'slug' => 'digital-growth-hub',
                'path' => '/digital-growth/',
                'category' => 'digital_growth',
                'status' => 'draft',
                'published' => false,
                'heading' => 'Search Growth, AEO & Performance Marketing Hub',
                'subheading' => 'Scaling organic customer acquisition, AI search citations, and digital revenue funnels.',
                'summary' => 'Central digital growth authority hub for SEO, AEO, and performance marketing strategies.',
                'primary_keyword' => 'Digital marketing expert Nepal',
                'seo_title' => 'Digital Growth Hub | SEO, AEO & Performance Marketing Expertise',
                'meta_description' => 'Digital growth strategies and search marketing leadership by Peshal Bhattarai.',
            ],
            [
                'title' => 'SEO Consultant & Organic Search Specialist in Nepal',
                'slug' => 'seo-consultant-nepal',
                'path' => '/digital-growth/seo-consultant-nepal/',
                'category' => 'digital_growth',
                'status' => 'draft',
                'published' => false,
                'heading' => 'Technical SEO Consultancy & Organic Audit Specialist',
                'subheading' => 'Driving top 3 Google keyword rankings and enterprise organic traffic.',
                'summary' => 'Expert SEO consultancy and site audit services in Nepal.',
                'primary_keyword' => 'SEO consultant Nepal',
                'seo_title' => 'SEO Consultant Nepal | Technical Search Audits & Ranking Strategy',
                'meta_description' => 'Senior SEO consultant in Nepal delivering verified search growth.',
            ],
            [
                'title' => 'Digital Marketing Services & Strategy in Nepal',
                'slug' => 'digital-marketing-nepal',
                'path' => '/digital-growth/digital-marketing-nepal/',
                'category' => 'digital_growth',
                'status' => 'draft',
                'published' => false,
                'heading' => 'Performance Marketing & Content Growth Funnels Nepal',
                'subheading' => 'Omnichannel digital growth, Google Ads, LinkedIn funnels, and ROI benchmarking.',
                'summary' => 'Full-suite digital marketing strategy and acquisition funnels in Nepal.',
                'primary_keyword' => 'Digital marketing Nepal',
                'seo_title' => 'Digital Marketing Nepal | Growth Marketing & Performance Ads',
                'meta_description' => 'Performance digital marketing and growth campaign management in Nepal.',
            ],
            [
                'title' => 'AI Search Optimization & AI SEO Strategy',
                'slug' => 'ai-seo',
                'path' => '/digital-growth/ai-seo/',
                'category' => 'digital_growth',
                'status' => 'draft',
                'published' => false,
                'heading' => 'Generative Engine Optimization (GEO) & AI Answer Engine Search',
                'subheading' => 'Optimizing brand content to cite inside ChatGPT, Perplexity, Claude, and AI Overviews.',
                'summary' => 'Next-generation AI SEO and Answer Engine Optimization (AEO) strategy.',
                'primary_keyword' => 'AI SEO',
                'seo_title' => 'AI SEO Strategy | Generative Engine & ChatGPT Citation Optimization',
                'meta_description' => 'AI SEO and Generative Engine Optimization strategy by Peshal Bhattarai.',
            ],
        ];

        foreach ($landingPages as $lp) {
            LandingPage::updateOrCreate(['slug' => $lp['slug']], $lp);
        }

        // 3. Seed Default Dynamic Navigation Menus
        $menus = [
            // Main Navbar
            ['menu_key' => 'main_nav', 'label' => 'Home', 'url' => '/', 'order' => 1],
            ['menu_key' => 'main_nav', 'label' => 'About', 'url' => '/about', 'order' => 2],
            ['menu_key' => 'main_nav', 'label' => 'Expertise', 'url' => '/services', 'order' => 3],
            ['menu_key' => 'main_nav', 'label' => 'Ventures', 'url' => '/ventures', 'order' => 4],
            ['menu_key' => 'main_nav', 'label' => 'Case Studies', 'url' => '/portfolio', 'order' => 5],
            ['menu_key' => 'main_nav', 'label' => 'Experience', 'url' => '/journey', 'order' => 6],
            ['menu_key' => 'main_nav', 'label' => 'Insights', 'url' => '/insights', 'order' => 7],
            ['menu_key' => 'main_nav', 'label' => 'Contact', 'url' => '/contact', 'order' => 8],

            // Footer Ventures
            ['menu_key' => 'footer_ventures', 'label' => 'Digital Terai', 'url' => '/ventures/digital-terai', 'order' => 1],
            ['menu_key' => 'footer_ventures', 'label' => 'IntechNexus', 'url' => '/ventures/intechnexus', 'order' => 2],
            ['menu_key' => 'footer_ventures', 'label' => 'BeinSEO Dubai', 'url' => '/ventures/beinseo-dubai', 'order' => 3],
            ['menu_key' => 'footer_ventures', 'label' => 'Thoplo Machine', 'url' => '/ventures/thoplo-machine', 'order' => 4],

            // Footer Legal
            ['menu_key' => 'footer_legal', 'label' => 'Privacy Policy', 'url' => '/privacy', 'order' => 1],
            ['menu_key' => 'footer_legal', 'label' => 'Terms of Service', 'url' => '/terms', 'order' => 2],
            ['menu_key' => 'footer_legal', 'label' => 'Resources', 'url' => '/resources', 'order' => 3],
            ['menu_key' => 'footer_legal', 'label' => 'Now', 'url' => '/now', 'order' => 4],
        ];

        foreach ($menus as $m) {
            SiteMenu::updateOrCreate(['label' => $m['label'], 'menu_key' => $m['menu_key']], $m);
        }

        $this->command->info("MasterVentureAndLandingPagesSeeder executed successfully!");
    }
}
